config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/menu'
  get 'static_pages/privacy_policy'

  devise_for :users
  resources :galleries
  resources :bands
  resources :events do
    collection do
        delete 'destroy_multiple'
    end
  end
  resources :welcomes

  root 'welcomes#landing'
  get 'welcomes/index' => 'welcomes#index'
  get '/calendar' => 'events#index'
  get '/band' => 'bands#index'
  get '/galleries' => 'galleries#index'

end

app/views/shared/_admin_buttons.erb
<%
  if params[:controller] == 'galleries'
    @path_name = 'gallery'
  else
    @path_name = params[:controller].chomp('s')
  end
%>
<%= link_to '#', :id => 'admin', :class => 'btn btn-primary btn-xs pull-right' do %>
  <i class="glyphicon glyphicon-wrench"></i>
<% end %>
<%= link_to send("new_#{@path_name}_path"), :class => 'btn btn-xs btn-success pull-right', :id => 'new', :"data-no-turbolink" => true do %>
  <i class="glyphicon glyphicon-plus"></i>
<% end %>

app/views/shared/_hours.erb
<h4 class='transparent-light pull-right hours'>
  <label>Hours:</label><br>
  Tuesday - Sunday: 5pm to 3am<br><br>
  <label>Happy Hour:</label><br>
  Tuesday - Sunday: 5pm to 7Pm<br><br>
</h4>

app/views/shared/_nav_buttons.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="navbar-collapse collapse navbar-responsive-collapse">
  <ul class="nav navbar-nav">
    <!-- <li><%= link_to "Dinner Menu", '#'%></li> -->
    <% if user_signed_in? && current_user.admin? %>

    <% end %>
    <li><%= link_to "Menu", static_pages_menu_path %></li>
    <li><%= link_to "Contact", static_pages_contact_path %></li>
    <li><%= link_to 'Events', 'https://www.facebook.com/nightowlnashville/events', target: 'none' %></li>
    <li><%= link_to "Gallery", galleries_path %></li>
    <li><%= link_to "About", static_pages_about_path %></li>
    <% if user_signed_in? && current_user.admin? %>
      <li><%= link_to "Bands", bands_path %></li>
      <li><%= link_to "Calendar", events_path%></li>
    <% end %>
    <!-- <li><%= link_to "Specials", '#' %></li> -->
  </ul>
</div><!-- /.navbar-collapse -->

app/views/shared/_privacy_policy.erb
<h4 class='transparent-light pull-right hours'>
  <label>Privacy Policy:</label><br>
  <p>
    Our gallery will display recent Instagram images labeled with #nightowlnashville.
    Images are never saved or used again.  The purpose is making our website's gallery a community
    experience recording good times at our venue/bar.  It offers immediate gratification for the user/customer
    when they get to see their picture on our website.
  </p><br>
</h4>