config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/menu'
  get 'static_pages/privacy_policy'

  devise_for :users
  resources :galleries
  resources :bands
  resources :events do
    collection do
        delete 'destroy_multiple'
    end
  end
  resources :welcomes

  root 'welcomes#landing'
  get 'welcomes/index' => 'welcomes#index'
  get '/calendar' => 'events#index'
  get '/band' => 'bands#index'
  get '/galleries' => 'galleries#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :band
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  require 'cgi'
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  # GET /events
  # GET /events.json
  def index
      @events = Event.all
      @events.each do |e|
        e.start_time = 0 if e.start_time.nil?
      end
    @events = @events.sort_by &:start_time
    get_bands
  end

  # GET /events/1
  # GET /events/1.json
  def show
    set_event
    @user = current_user
  end

  # GET /events/new
  def new
    @event = Event.new
    @date = params["date"]
    get_bands
  end

  # GET /events/1/edit
  def edit
    get_bands
  end

  # POST /events
  # POST /events.json
  def create
    if params[:band_id].blank?
      @band = Band.new()
      @band.name = params[:new_name]["{:class=>\"text_field form-control\"}"]
      params[:band_id] = @band.id
      @band.save
    end

    if @band == nil
      @band = Band.find(params[:band_id])
    end
    @event = @band.events.create(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
        format.js { render :new, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def destroy_multiple

  Event.destroy(params[:events])

  respond_to do |format|
    format.html { redirect_to events_path }
    format.json { head :no_content }
  end

end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def get_bands
      @bands = Band.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :confirmed, :band_id, :description, :start_time, :end_time, :new_name)
    end

    def authorize_admin
      redirect_to :events, :status => 401 unless current_user && current_user.admin?
      #redirects to previous page
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
  <%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
<div class="form-group">
  <%= f.label :confirmed, :class => 'control-label col-md-2'%>
    <div class="col-md-9">
      <%= check_box_tag :confirmed, class: 'text_field form-control' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :band_id, :class => 'control-label col-md-2'%>
    <div class="col-md-9">
      <%= select_tag :band_id, options_from_collection_for_select(@bands, 'id', 'name'), class: "form-control", prompt: 'Select Band' %>
      <%= text_field :new_name, class: 'text_field form-control' %>
  </div>
</div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-9">
      <%= f.text_field :title, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-9">
      <%= f.text_area :description, :class => 'text_field form-control' %>
    </div>
  </div>
  <row>
    <div class="form-group">
      <%= f.label :start_time, :class => 'control-label col-md-2' %>
      <div class="col-md-9">
        <div id="startdatetime-from" class="input-append date">
          <%= f.datetime_select :start_time, :class => 'text_field form-control', :id =>'datetimepicker6', :required => true, :default => @date %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :end_time, :class => 'control-label col-md-2' %>
      <div class="col-md-9">
        <%= f.datetime_select :end_time, :class => 'text_field form-control', :id =>'datetimepicker7' %>
      </div>
    </div>
  </row>
  <div class="form-group">
    <div class='col-md-offset-2 col-md-9'>
      <%= f.submit nil, :id => 'submit', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  events_path, :class => 'btn btn-default', :"data-no-turbolink" => true %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>: <%=@event.band.name + ' ' + @event.start_time.strftime('%m/%d/%Y')%></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>

  <h1 class='text-center transparent-light'>Night Owl Calendar</h1>
  <table class="table hidden">
    <%= form_tag destroy_multiple_events_path, method: :delete do %>
    <% if user_signed_in? && current_user.admin? %>
    <div class='col-md-12 hidden' id='delete-multiple'>
      <%= submit_tag 'Delete Selected', class: 'form-control col-md-12 btn-danger' %></p>
    </div>
    <% end %>
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:confirmed) %></th>
        <th><%= model_class.human_attribute_name(:start_time) %></th>
        <th><%= model_class.human_attribute_name(:artist) %></th>
        <th><%= model_class.human_attribute_name(:title) %></th>
        <th><%= model_class.human_attribute_name(:description) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <% if event.start_time > Date.today %>
          <tr>
            <td>
            <%= glyph(:check) if event.confirmed %>
            <%= glyph(:unchecked) if !event.confirmed %></td>
            <td><%=l event.start_time, format: :short if event.start_time? %></td>
            <% if event.band %>
              <td><%= event.band.name %></td>
            <% end %>
            <td><%= event.title %></td>
            <% if event.description %>
              <td>Present</td>
            <% else %>
              <td>Not Present</td>
            <% end %>
            <td><%=l event.created_at, format: :short %></td>
            <td>
              <%= link_to event_path(event), :class => 'btn btn-xs btn-warning', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
                <%= glyph 'info-sign' %>
              <%- end -%>
              <%= link_to edit_event_path(event), :class => 'btn btn-xs btn-primary', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }", :"data-no-turbolink" => true do %>
                <%= glyph 'pencil' %>
              <%- end -%>
              <%= link_to event_path(event), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
                <%= glyph 'remove' %>
              <%- end -%>
              <%= check_box_tag "events[]", event.id %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<div class='col-md-12' id='calendar'></div>
<% end %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<%=@date%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to edit_event_path(@event), :class => 'btn btn-warning btn-xs pull-right', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
    <%= glyph 'pencil' %>
  <% end %>
  <%= link_to event_path(@event), :class => 'btn btn-danger btn-xs pull-right', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }", :method => 'delete', :data => { :confirm => t('.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?'))} do %>
    <%= glyph 'trash' %>
  <% end %>
<% end %>
<div class="page-header">
  <h1 id='event-headline' class='text-center'><%= @event.start_time.strftime("%m/%d/%Y") + " @ The Night Owl " + @event.start_time.strftime("%I:%M%p") %>
    <% if @event.end_time? %>
      <%= " - " + @event.end_time.strftime("%I:%M%p") %>
    <% end %>
    <%= link_to events_path, :class => 'btn btn-default btn-xs pull-left', :title => "#{ t('.back', :default => t('helpers.links.back')) }" do %>
      <%= glyph 'arrow-left' %>
    <% end %>
  </h1>
</div>
<div class='row'>
  <h1 class="prettyprint text-center transparent-light"><%= @event.title %></h1>
  <% if @event.description? %>
    <p class='transparent-light'>
      <%= @event.description %>
    </p>
    <% end %>
</div>
<div class='row'>
  <div class='row header transparent-light'>
      <% if @event.band.avatar? %>
        <%= image_tag (@event.band.avatar), class: 'col-xs-4 img img-responsive transparent-dark'  %>
      <% else %>
        <h1><%= link_to @event.band.name, band_path(@event.band_id) %></h1>
      <% end %>
    <p>
    <% if @event.band.hometown %>
      <%= @event.band.hometown + " - "%>
    <% end %>
    <% if @event.band.bio %>
      <%= @event.band.bio %>
      <% end %>
      <div class='clear-fix'></div>
      </p>
      <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <% if @event.band.link2? %>
          <%= link_to 'Website',@event.band.link2 , target: 'none', class:'btn btn-info' %>
        <% end %>
        <% if @event.band.link3? %>
          <%= link_to "Facebook", @event.band.link3, target: 'none', class: 'btn btn-info' %>
        <% end %>
    </div>
  </div>
  <div class='transparent-light'>
    <div class='row'></div>
    <% if @event.band.link %>
      <div class='embed-responsive embed-responsive-16by9'><%= content_tag(:iframe, '', class: 'embed-responsive-item', src: @event.band.link,
                   width: 560, height: 315, frameborder: 0) %></div>
    <% end %>
  </div>
</div>