config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/menu'
  get 'static_pages/privacy_policy'

  devise_for :users
  resources :galleries
  resources :bands
  resources :events do
    collection do
        delete 'destroy_multiple'
    end
  end
  resources :welcomes

  root 'welcomes#landing'
  get 'welcomes/index' => 'welcomes#index'
  get '/calendar' => 'events#index'
  get '/band' => 'bands#index'
  get '/galleries' => 'galleries#index'

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]
  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all.order(:role)
    @main_welcome = Welcome.where(role: 'main')
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def landing
    render layout: "landing_layout"
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.require(:welcome).permit(:title, :notes, :headline, :role)
    end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_form.html.erb
<%= form_for @welcome, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :headline, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :headline, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :notes, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :notes, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :role, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :role, :class => 'text_field form-control' %>
    </div>
    <p class='transparent-dark'>
      Role is used for what is displayed where on the welcome page.
      Options:
      main - Main is the top welcome
      hidden - This way you can remove a welcome from the homepage without deleting it
      number - Welcomes will be ordered by number given
    </p>
  </div>
  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  welcomes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<%- model_class = Welcome -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/welcomes/index.html.erb
<%- model_class = Welcome -%>
<div class='share row'>
  <a href="https://twitter.com/share" class="twitter-share-button col-md-4" data-text="The Night Owl - Nashville's coolest New Boogie Bar and Grill!" data-via="RockinRandallBo" data-count="none" data-hashtags="NigthOwlNashville">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  <a href="https://twitter.com/nashnightowl" class="twitter-follow-button" data-show-count="false">Follow @nashnightowl</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  <div class="fb-like" data-href="https://www.facebook.com/nightowlnashville" data-layout="button" data-action="like" data-share="true"></div>
  <%= link_to 'https://www.instagram.com/nightowlnashville/', class:'btn btn-default btn-instagram' do %>
    <%= image_tag 'instagram_logo', class:'img img-responsive' %>
  <% end %>
  <%= render 'shared/hours' %>
</div>
<% if user_signed_in? && current_user.admin? %>
  <% @welcomes.order(:role).each do |welcome| %>
    <div id='admin-container'>
      <table bgcolor="#00FF00" class="table hidden">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:role) %></th>
            <th><%= model_class.human_attribute_name(:header) %></th>
            <th><%= model_class.human_attribute_name(:headline) %></th>
            <th><%= model_class.human_attribute_name(:notes) %></th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= welcome.role %></td>
              <td><%= welcome.title %></td>
              <td><%= welcome.headline %></td>
              <td><%= welcome.notes %></td>
            <td>
              <%= link_to welcome_path(welcome), :class => 'btn btn-xs btn-warning', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
                <%= glyph 'info-sign'%>
              <%- end -%>
              <%= link_to edit_welcome_path(welcome), :class => 'btn btn-xs btn-primary', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
                <%= glyph 'pencil' %>
              <%- end -%>
              <%= link_to welcome_path(welcome), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
                <%= glyph 'remove' %>
              <%- end -%>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>
<div class="row news-item">
  <% if @main_welcome[0] %>
    <div class="news-header transparent-dark text-center"><h1><%= @main_welcome[0].title %></h1></div>
    <h3 class='transparent-light news-headline text-center accent-border'><%= @main_welcome[0].headline %></h3>
    <p class='transparent-light news-notes'><%= @main_welcome[0].notes %></p>
  <% end %>

  <% @welcomes.each do |welcome| %>
    <% unless (welcome.role == 'main' || welcome.role == 'hidden') %>
      <div class="news-header transparent-dark text-center"></div>
      <% if welcome.title? %>
        <div class="news-header2 transparent-light text-center"><h2><%= welcome.title %></h2></div>
      <% end %>
      <% if welcome.headline? %>
        <h4 class='transparent-light news-headline text-center'><%= welcome.headline %></h4>
      <% end %>
      <% if welcome.notes? %>
      <p class='transparent-light news-notes'><%= welcome.notes.html_safe %></p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/welcomes/landing.html.erb
<div>
  <%= link_to 'Enter', welcomes_path, class:'btn btn-default col-md-12', id: 'click'%>
  <%= image_tag('night-owl-logo', id: 'landing-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
</div>
<h1 class='text-center'>Click the owl and have a hoot!
</h1>
<div class='col-md-offset-6 checkbox pull-left'>
  <%= glyph 'volume-off' %>
</div>
<div class='checkbox pull-left'>
  <label>
    <%= check_box_tag 'Mute', id: 'mute', class:'checkbox' %>
  </label>
</div>
<%= audio_tag 'horned_owl.wav', id: 'owl-hoot' %>

app/views/welcomes/new.html.erb
<%- model_class = Welcome -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/welcomes/show.html.erb
<%- model_class = Welcome -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @welcome.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:notes) %></dt>
      <dd><pre class="prettyprint"><%= @welcome.notes %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:headline) %></dt>
      <dd><pre class="prettyprint"><%= @welcome.headline %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:role) %></dt>
      <dd><pre class="prettyprint"><%= @welcome.role %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              welcomes_path, :"data-no-turbolink" => 'true', :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_welcome_path(@welcome), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              welcome_path(@welcome),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>