config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/menu'
  get 'static_pages/privacy_policy'

  devise_for :users
  resources :galleries
  resources :bands
  resources :events do
    collection do
        delete 'destroy_multiple'
    end
  end
  resources :welcomes

  root 'welcomes#landing'
  get 'welcomes/index' => 'welcomes#index'
  get '/calendar' => 'events#index'
  get '/band' => 'bands#index'
  get '/galleries' => 'galleries#index'

end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :events, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  layout 'bands_layout', only: [:index]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all.sort_by &:name
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
    set_band
    @events = Event.where(band_id: @band.id)
    @event = @events[0]
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)
    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_band
    @band = Band.find(params[:id])
    if @band.link?
      str = @band.link
      str = str.gsub('watch', 'embed');
      @band.link = str
      @band.save
    end
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def band_params
    params.require(:band).permit(:name, :bio, :link, :link2, :link3, :avatar, :remote_avatar_url, :hometown)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for @band, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :hometown, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :hometown, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :avatar, :class => 'control-label col-md-2' %>
    <%= image_tag @band.avatar_url(:thumb), class: 'img img-responsive' if @band.avatar? %>
    <div class="col-md-10">
      <%= f.file_field :avatar, class: 'pull-right form-control col-md-10' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :remote_avatar_url, "or image URL", :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :remote_avatar_url, :class => 'text_field form-control col-md-10' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bio, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :bio, :class => 'text_field form-control col-md-12' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :youtube, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :link, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :website, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :link2, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :facebook, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :link3, :class => 'text_field form-control' %>
    </div>
  </div>
  </div>
  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :id => 'submit', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  bands_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/bands/edit.html.erb
<%- model_class = Band -%>
<div class="page-header">
  <h1 class='text-center'><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bands/index.html.erb
<%- model_class = Band -%>
<div class="shared/page-header text-center transparent-light">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table hidden">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.id %></td>
        <td><%= band.name %></td>
        <td><%= band.link %></td>
        <td><%=l band.created_at, format: :short %></td>
        <td>
          <%= link_to band_path(band), :class => 'btn btn-xs btn-warning', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_band_path(band), :class => 'btn btn-xs btn-primary', :"data-no-turbolink" => 'true', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to band_path(band), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class='transparent-dark'>
  <h2>
    <% @bands.each do |band| %>
      <%= link_to band_path(band), :class => 'btn btn-lg text-center text-warning band-name', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
        <h2><%= band.name %></h2>
       <%end%>
    <% end %>
  </h2>
</div>

app/views/bands/new.html.erb
<%- model_class = Band -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bands/show.html.erb
<%- model_class = Band -%>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to edit_band_path(@band), :class => 'btn btn-warning btn-xs pull-right', :"data-no-turbolink" => 'true', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
    <%= glyph 'pencil' %>
  <% end %>
  <%= link_to band_path(@band), :class => 'btn btn-danger btn-xs pull-right', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }", :method => 'delete', :data => { :confirm => t('.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?'))} do %>
    <%= glyph 'trash' %>
  <% end %>
<% end %>
<div class="page-header">
  <h1 class='text-center'><%=t '.title', :default => model_class.model_name.human.titleize %>
    <%= link_to bands_path, :class => 'btn btn-default btn-xs pull-left', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
      <%= glyph 'arrow-left' %>
    <% end %>
  </h1>
  <h1 class="text-center transparent-light prettyprint"><% if @band.name %><%= @band.name %><% end%> - <% if @band.hometown %> <%=@band.hometown %><% end %></h1>
  <% if @events.length > 0 %>
  <h4 class='text-center transparent-dark prettyprint'>Live @ the night owl -><%= @event.start_time.strftime('%m/%d/%Y') %></h4>
  <% end %>
<div class='row header transparent-light'>
    <% if @band.avatar? %>
      <%= image_tag (@band.avatar), class: 'col-xs-4 img img-responsive transparent-dark'  %>
    <% end %>
  <p>
  <% if @band.hometown %> <%=@band.hometown %><% end %> -
  <% if @band.bio %> <%=@band.bio %><% end %>

    <div class='clear-fix'></div>
    </p>
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
      <% if @band.link2? %>
        <%= link_to 'Website',@band.link2 , target: 'none', class:'btn btn-info' %>
      <% end %>
      <% if @band.link3? %>
        <%= link_to "Facebook", @band.link3, target: 'none', class: 'btn btn-info' %>
      <% end %>
    </div>
    <div class='embed-responsive embed-responsive-16by9'><%= content_tag(:iframe, '', class: 'embed-responsive-item', src: @band.link, width: 560, height: 315, frameborder: 0) %></div>
  </div>
</div>